version: "3"

services:
  # server:
  #   build:
  #     context: ./server/
  #     dockerfile: Dockerfile.dev
  #   command: /usr/app/node_modules/.bin/nodemon -L /src/App.js
  #   volumes:
  #     - ./server/:/usr/app
  #     - /usr/app/node_modules
  #   ports:
  #     - "8888:8888"
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #     - NODE_ENV=development

  #######################################################
  #  EventStoreDB
  #######################################################
  eventstoredb:
    image: eventstore/eventstore:21.10.2-buster-slim
    # use this image if you're running ARM-based proc like Apple M1
    # image: ghcr.io/eventstore/eventstore:21.10.0-alpha-arm64v8
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore
    networks:
      - esdb_network

  mongodb:
    image: mongo:5.0
    # environment:
    #     MONGO_INITDB_ROOT_USERNAME: root
    #     MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db

networks:
  esdb_network:
    driver: bridge

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
  mongodb-data:
